PureBasicDebugger/DebugOutput.pb
PureBasicDebugger/PureBasic.asm
PureBasicDebugger/Standalone_ScintillaStuff.pb
PureBasicDebugger/VariableDebug.pb
PureBasicIDE/CompilerFlags.pb
PureBasicIDE/CompilerInterface.pb
PureBasicIDE/CompilerWindow.pb
PureBasicIDE/EditHistory.pb
PureBasicIDE/Explorer.pb
PureBasicIDE/FormDesigner/gadgetitemswindow.pb
PureBasicIDE/FormDesigner/opensave.pb
PureBasicIDE/HilightningFunctions.pb
PureBasicIDE/IDEDebugger.pb
PureBasicIDE/Preferences.pb
PureBasicIDE/ProjectManagement.pb
PureBasicIDE/ProjectPanel.pb
PureBasicIDE/PureBasic IDE.pbp
PureBasicIDE/RecentFiles.pb
PureBasicIDE/ScintillaHilightning.pb
PureBasicIDE/ShortcutManagement.pb
PureBasicIDE/SourceManagement.pb
PureBasicIDE/StructureViewer.pb
PureBasicIDE/TabBarGadget.pbi
PureBasicIDE/UpdateCheck.pb
PureBasicIDE/UserInterface.pb
PureBasicIDE/WindowsMisc.pb
PureBasicIDE/data/SilkTheme/Readme.txt
README.md

Change every occurrence of `http://` links to `https://` (both in source code files and documents) for the following URLs:
* www.spiderbasic.com
* www.purebasic.com
* www.purebasic.fr
(fixes #9)

Fix HTTP Links to HTTPS

---

.gitattributes
README.md

* In `.gitattributes` add rules to exclude Git-related contents from the  downloadable Zip archive of the repository, for the sake of end users  only interested of getting a copy of the IDE sources. (See #14)
* Add to README doc instructions on how to download the project:
1. Download ZIP Archive
2. Clone locally via Git
3. Fork on GitHub
(resolves #14)

Export Ignore Rules + Download Instructions

---

README.md

Create at [Git.io](https://git.io/) a short vanity URL pointing to the repository and add it to main README:
* https://git.io/purebasic
This should simplify memorizing the repository URL and adding it as a signature in email and forum posts.

Add Vanity URL

---

PureBasicIDE/CompilerFlags.pb
PureBasicIDE/ProjectManagement.pb
PureBasicIDE/PureBasic IDE.pbp
PureBasicIDE/UpdateCheck.pb

The PB IDE 5.71 and earlier check for HTTP namespaces in project files and the update check XML file. The change to HTTPS namespaces in PR #10 broke backwards compatibility.
This pull request reverts the namespaces to HTTP, but keeps HTTPS for web links presented to the user. It also uses new named constants rather than repeated string literals.

Use HTTP namespace constants for backwards compatibility

---

PureBasicDebugger/Data/README.md
PureBasicIDE/data/DefaultTheme/README.md
PureBasicIDE/data/README.md
PureBasicIDE/data/SilkTheme/README.md
PureBasicIDE/data/SpiderBasic/README.md
PureBasicIDE/data/SpiderBasic/ReadMe Icon.txt
README.md

These commits all relate to adding README files to various subfolders, providing info about their contents and image previews.
The goal is to improve the navigation experience and contents discovery on GitHub WebUI, reducing the overwhelming impact of a project that contains so many files. The ultimate goal is to provide in each folder a README file that allows end users to grasp what's there and what does what, without having to leave the page in order to peek at previews of single files (code or image) or folders.
I've kept the commits separate, instead of squashing them together into a huge single commit, because this is a long term task and more commits of this type are on the way anyhow, so it's worth keeping them to human-manageable sizes.

Add Images Previews in README Files

---

PureBasicIDE/CompilerWindow.pb
PureBasicIDE/dialogs/Build.xml

Add an Escape shortcut to the Build All window — but only allow it once all targets are finished.
It maps the shortcut's Menu event to a "Close" Gadget event, like the Find and About windows do.
I'm pulling to `master` because a `development` branch hasn't been created yet — should be OK for VERY simple features like this!

Add Escape shortcut to close Build Window

---

.gitignore
BUILD.md
PureBasicIDE/PureBasic IDE.pbp
PureBasicIDE/PureBasic.pb
PureBasicIDE/WindowsMisc.pb

Here are some small changes which I think improve the repo:
- Set Git to ignore the generated `Build` subfolder
- Remove the hard-coded constant `#PureBasicPath` which doesn't seem to be used anymore
- Change `#BUILD_DIRECTORY` from a hard-coded absolute path to a relative path
- Set `PureBasicPath$` to `#PB_Compiler_Home` instead of a hard-coded path
- Prevent 2 debugger errors whenever `Scintilla.dll` is not found (can happen a lot while getting the repo up-and-running)

Git compliance improvements/cleanup

---

.travis.yml
PureBasicDebugger/Communication.pb
PureBasicDebugger/Communication_PipeUnix.pb
PureBasicDebugger/DebuggerCommon.pb
PureBasicDebugger/History.pb
PureBasicDebugger/MemoryViewer.pb
PureBasicDebugger/Standalone_Common.pb
PureBasicDebugger/Standalone_Preferences.pb
PureBasicDebugger/Standalone_ScintillaStuff.pb
PureBasicDebugger/VariableDebug.pb
validate.sh

The firs of these two commits solves the problem of IDE Settings creeping into the repository files accidentally (as discussed in #15). In the end, I opted to use GREP to check for the presence of IDE setting in any PB sources (`*.pb`, `*.pbi`, `*.pbf`).
The second commit removes IDE settings from a number of sources that still had them (not sure if they were there before or if they creped back with some recent PR).

Check for IDE Settings in Travis Build

---

CONTRIBUTING.md
README.md

Create `CONTRIBUTING.md` doc with guidelines on how to contribute to the repository and Wiki. The document also provides a "Useful Links" section for Git newbies. 
The guidelines are still work-in-progress, and shall be updated once a clear strategy has been set forth regarding development branches and tagged releases.
They also mention PureBasic IDE settings safeguards (see #15) to prevent spurious changes to tracked source files; but they do not cover yet the issues regarding PureBasic projects files (which still need to be addressed in the repository).
Update main `README.md`:
- Include references to the new Contributors' Guidelines.
- In "Acknowledgements", mention Danilo Krahn and Gaetan Dupont-Panon  (see #21).

Add Contributors' Guidelines

---

PureBasicIDE/AboutWindow.pb
PureBasicIDE/MacExtensions.pb
PureBasicIDE/Preferences.pb
PureBasicIDE/ProjectManagement.pb
PureBasicIDE/SourceManagement.pb
PureBasicIDE/UserInterface.pb
README.md

Adds a basic dark mode and theme accent support to the IDE (needs to be compiled with a recent XCode).
What it does in details:
1. Adds Cocoa-specific procedure GetCocoaColor(), tuned to support older macOS versions down to 10.4.
2. Explicitly sets window color to [windowBackgroundColor](https://developer.apple.com/documentation/appkit/nscolor/1528630-windowbackgroundcolor?language=objc) to mitigate the lack of transparency support in TabBarGadget and StatusBar.
3. Sets mode-specific colors for TabBarGadget.
4. Adds a Monokai theme to Preferences - one of the most popular dark themes that fits perfectly to macOS dark mode.
I tried to make it as non-intrusive as possible and this is the bare minimum.
Limitations:
1. No support for theme switching on the fly, since it requires a large …

Dark mode support for macOS

---

PureBasicIDE/FormDesigner/mainevents.pb

PB 572 b1: IDE Formdesigner display problem setting parent
https://www.purebasic.fr/english/viewtopic.php?f=4&t=74526
- Height of the ComboBoxGadgets was too less
- Second TextGadget was not wide enough for the German text
Sorry, but only tested under Linux.

Fix display errors in window '#WINDOW_Form_Parent' of the FormDesigner

---

PureBasicDebugger/Communication_Network.pb
PureBasicIDE/CompilerInterface.pb
PureBasicIDE/EditHistory.pb
PureBasicIDE/FileSystem.pb
PureBasicIDE/ProcedureBrowser.pb
PureBasicIDE/ProjectManagement.pb
PureBasicIDE/UserInterface.pb
PureBasicIDE/ZLib.pb

This is a new version of PR #47 , based off the latest `master` to solve conflicts, so I will repeat the description here:
> There are some places in the code with "unbalanced" keywords (multiple opening keywords in CompilerIf/CompilerElse blocks, with only one closing keyword). This causes the keyword highlighter, "Go to matching keyword", and the auto-indenter to not work correctly.
> 
> This PR makes tiny code changes to "balance" all keywords. Unfortunately this creates very large diffs because the indentation for the rest of the file is changed (fixed!)
Notes:
- Warning, this looks like a huge `diff` because of all the indentation changes. I recommend you "hide whitespace changes" in `git-gui` or use `?w=1` on GitHub, to review the changes. The "Split" view on GitHub also helps.
- …

Balance keywords to fix incorrect indentation

---

PureBasicIDE/Common.pb
PureBasicIDE/Declarations.pb
PureBasicIDE/Language.pb
PureBasicIDE/ScintillaHilightning.pb
PureBasicIDE/ShortcutManagement.pb
PureBasicIDE/UserInterface.pb

This PR adds 5 new user-configurable keyboard shortcuts, most are built-in Scintilla functions:
- Move selected lines up
- Move selected lines down
- Delete selected lines
- Duplicate selection
- Paste as comment
Notes / judgment calls:
- `Paste as comment` is specific to PB syntax, so it's a custom function. The other 4 are just calls to Scintilla functions. See comments in `UserInterface.pb`
- Based on Scintilla's defaults and other text editors, I gave 4 of the 5 default defined shortcuts, except `Delete selected lines`, which the user has to set.
- Another judgment call, I added `Paste as comment` to the menus under `Paste`. The other 4 are not in the menus, so they are grouped at the bottom of the preferences list (near `Shift comments to the right/left`).
- The new shortcut names …

New editor shortcut functions

---

PureBasicIDE/FormDesigner/FormManagement.pb
PureBasicIDE/FormDesigner/mainevents.pb

As I wrote [here](https://github.com/fantaisie-software/purebasic/pull/41#issuecomment-583028184), Form Designer needs a little fix to support dark mode. This PR makes it follow macOS system colors.

[macOS] Dark mode fix for form designer

---

PureBasicDebugger/MemoryViewer.pb
PureBasicIDE/AssemblyOperandsX86.pb
PureBasicIDE/FormDesigner/FormManagement.pb
PureBasicIDE/IDEDebugger.pb
validate.sh

Update `validate.sh` to check for trailing whitespace (tabs or spaces) in lines that contain at least one non-whitespace character (i.e. don't consider indentation-only lines as trailing whitespace, because the PB IDE formatter allows them).
Now all PB sources with trailing space will fail the Travis CI checks.
I've tested it live with the latest merge of PR #53, which contained some trailing spaces (as pointed out by @SicroAtGit), and it correctly failed the build listing all PB files that didn't meet the requirements:
https://travis-ci.com/tajmone/purebasic/builds/148020124

Check PB Sources for Trailing WS

---

PureBasicIDE/Common.pb
PureBasicIDE/Declarations.pb
PureBasicIDE/Language.pb
PureBasicIDE/Preferences.pb
PureBasicIDE/ScintillaHilightning.pb
PureBasicIDE/ShortcutManagement.pb
PureBasicIDE/UserInterface.pb

This PR does three related things: 
1. Add 3 zoom keyboard shortcuts (Zoom In, Out, Default) based on Scintilla's zoom functions
2. Synchronize zoom across all open files
3. Fix a bug in the shortcut table (the last item was not being used)
Shortcuts notes:
- On Windows, I *really* think zoom should use the standard Ctrl+Plus Ctrl+Minus hotkeys, so I defaulted them to `#VK_OEM_PLUS` and `#VK_OEM_MINUS`. I know these are not native PB constants, but Microsoft guarantees they're correct on all keyboard regions, unlike the brackets, semicolon, etc.
- I extended the shortcut name table from 103 to 107. 104-105 were already listed as NumLock and ScrollLock but not being used (any reason?). 106-107 are now the Plus and Minus keys (different from NumPad Add and Subtract).
- On Mac/Linux I did …

Add zoom keyboard shorcuts

---

PureBasicIDE/GrepWindow.pb

If the output window (#WINDOW_GrepOutput) was closed during a running
search, it was still possible to abort the search with a click on the
Stop button, but the Start and Cancel button was then not re-enabled.
https://www.purebasic.fr/english/viewtopic.php?f=4&t=71539

Fix re-enable buttons bug in window 'Find in Files' (#WINDOW_Grep)

---

PureBasicIDE/ScintillaHighlighting.pb

This fixes a minor bug in the "Repeated Selections Background" feature.
If you select a word (such as `EndIf`) it highlights all other occurrences. But if it occurs at the *very end of the file* (no newline) that one is not highlighted.
This fixes it by changing the boundary of the `While` loop from a `<` to `<=` check.
For example, if the selection length is 5 (`EndIf`) and the source length is 100 bytes, the final check of the loop should be bytes `95–99` (0-based). Previously it was stopping the loop one byte before that.

Fix highlight of matching word at end of file

---

PureBasicDebugger/MemoryViewer.pb

The Memory Viewer setting 'Display Hex values' was set when compiling the IDE and not at runtime when opening the Memory Viewer. As a result, changing this setting had no effect.
[PB 5.71 x64] "Display Hex values" and MemoryViewer
https://www.purebasic.fr/english/viewtopic.php?f=23&t=74272

Fix Memory Viewer 'Display Hex values' setting

---

BUILD.md
README.md

* In the `BUILD.md` document (see #30):
* Refer Windows users to the new Zip archive with the required GNU utilities, prepared by @ChrisRfr, downloadable from the Wiki.
* Drop all references to the UnxUtils package.
* Polish document contents.
* In main `README.md` document:
* Credit @ChrisRfr in the Acknowledgements section. (see #30)
* Sort credited people alphabetically.

UnxUtils Alternatives

---

PureBasicIDE/ScintillaHighlighting.pb

This PR fixes the IDE freezing (infinite loop) when performing a Find Previous with "Don't search in comments" or "Don't search in strings" checked.
If you perform a Find Previous, and find an occurrence, but it's ignored (comment or string), then the loop repeats the search in the same position forever. This PR handles that case and ensures the search location is moved correctly.
Somebody from the PB team should review this, because they know better than I do how the Find/Replace system works.
Simple dummy code to test it:
ifififif
; if
"if"
ifififif
Try searching for `if`, Forward and Backward, with and without "Don't search in comments" and "Don't search in strings" checked.
Forum posts:  
https://www.purebasic.fr/english/viewtopic.php?f=4&t=70161 …

Bug fix for "Find Previous" freezing

---

PureBasicDebugger/MemoryViewer.pb

Setting the checkbox has no effect if the view type is `Hex` or `String`. Therefore, the checkbox should be deactivated in these cases to avoid confusion.
https://www.purebasic.fr/english/viewtopic.php?p=550837#p550837

Add deactivation of the `Data` checkbox in the Memory Viewer

---

PureBasicIDE/ProjectManagement.pb

This is a small code-cleanup PR which replaces ProjectOpenMode number literals with named constants, in preparation for more work on the Project system.

Replace ProjectOpenMode numbers with named constants

---

PureBasicIDE/FormDesigner/mainevents.pb

Fix Gadgets Offset with Drag n Drop in FormDesigner
Place the Gadget on the mouse position using the same alignment FD_AlignPoint() as in FD_Move() with topwinpadding, leftpadding, Page_Padding...

Fix Gadgets Drag n Drop Position  in FormDesigner

---

PureBasicIDE/CodeViewer.pb
PureBasicIDE/Common.pb
PureBasicIDE/Declarations.pb
PureBasicIDE/DiffWindow.pb
PureBasicIDE/Language.pb
PureBasicIDE/Preferences.pb
PureBasicIDE/ScintillaHighlighting.pb
PureBasicIDE/WindowsMisc.pb
PureBasicIDE/dialogs/Preferences.xml

This PR allows the user to customize what characters Scintilla considers "word characters", for example when double-clicking to select a variable name. It also affects Find/Replace > "Whole words only" behavior.
Notes:
- This is a compromise of PR #66 and and #67 , see those discussions
- I left the defaults as-is (`$#*@`). Should we add `%` or remove `@`?
- I added it to the Preferences under Editor > Editing per @t-harter 
- I labeled it "Word characters" but we could use a better description
- This requires you to run `make` again because the Preferences dialog XML changed
- I moved the `SCI_SETWORDCHARS` call into a procedure, so it can be called at Scintilla creation OR applying changed preferences
- Because it's user-customizable now, I added some basic checks (disallow whitespace …

Make Scintilla word chars a user preference

---

PureBasicIDE/Common.pb
PureBasicIDE/FormDesigner/FormParent.xml
PureBasicIDE/FormDesigner/mainevents.pb

By using the Dialog-Lib the window and the contained gadgets are automatically adjusted in size and position according to the contents. This avoids an oversized window with too much empty space on all
operating systems.
Improvement of pull request #50.
PB 572 b1: IDE Formdesigner display problem setting parent
https://www.purebasic.fr/english/viewtopic.php?f=4&t=74526

Replace the window `#WINDOW_Form_Parent` with a dialog window

---

PureBasicIDE/HighlightingEngine.pb
PureBasicIDE/KeywordsData.pbi

Take the `DataSection` with the keywords definitions from "HighlightingEngine.pb"and move it to "KeywordsData.pbi", so that third party tools can gain access to all the PureBasic/SpiderBasic keywords definitions.
See Issue #88 for more info.

Move BASIC Keywords to Independent File

---

PureBasicIDE/ProjectManagement.pb
PureBasicIDE/SourceManagement.pb
PureBasicIDE/UserInterface.pb

There were [some complaints about tab colors combination](https://www.purebasic.fr/english/viewtopic.php?p=557313#p557313) and now i see that it was indeed a bad decision to enforce system color on TabBarGadget. This PR reverts altered tab colors to their original state, all other changes related to dark mode support stay the same, including TabBarGadget background.
I still think that TabBarGadget needs an extensive rework to be able to support system themes, maybe someone someday will do that or try to approach this problem differently.

[macOS] Revert TabBarGadget tab colors

---

PureBasicIDE/AutoComplete.pb
PureBasicIDE/ProcedureBrowser.pb
PureBasicIDE/SourceManagement.pb

Linux fix AutoComplete Redraw TreeView.
Linux fix ProcedureBrowser Crash. The g_object is not valid.

Fix AutoComplete and ProcedureBrowser

---

PureBasicIDE/Common.pb
PureBasicIDE/Language.pb
PureBasicIDE/Preferences.pb
PureBasicIDE/ScintillaHighlighting.pb
PureBasicIDE/dialogs/Preferences.xml

This patch introduces a new option in Preferences/Editor to indent selected source code with [Strg] + [i] based on the Tab length instead of the next function key word (default):
This is the current indentation behaviour:
This would be the indentation with the new option "Indent with Tab length" enabled and a Tab width of 2:
I had posted this request already in the PureBasic forum:
https://www.purebasic.fr/english/viewtopic.php?f=14&t=74151&start=71
Unfortunately there are also the following changes in the folder _catalogs_ necessary. The folder _catalogs_ is currently not contained in the purebasic repository!
English _catalogs/Editor.catalog_:
Insert in line 337:
`TabIndent              = Indent with Tab length`
German _catalogs/Deutsch/Editor.catalog_:
Insert in line 337:
`TabIndent …

New indentation option

---

PureBasicIDE/Common.pb
PureBasicIDE/ProjectPanel.pb
PureBasicIDE/ScintillaHighlighting.pb
PureBasicIDE/SourceManagement.pb
PureBasicIDE/SourceParser.pb
PureBasicIDE/UserInterface.pb
Window-x86.cmd

In `Windows-x86.cmd` a comment tells you to specify the path of an `x64` installation - I think this is supposed to be `x86`.
While submitting this tiny correction, I'm also fixing misspellings of `special` :grin:

Fix wrong "x64" reference, and some misspellings

---

PureBasicIDE/Preferences.pb

Fixes #101 reported by @SicroAtGit .
In the default color schemes DataSection, `#COLOR_GlobalBackground` values are incorrectly labeled as `#COLOR_ASMKeyword` in their comments.
(And `#COLOR_GlobalBackground` was not mentioned anywhere!)
This also labels the `ToolsPanel` values for extra clarity.

Fix wrong #COLOR comments in DefaultColorSchemes DataSection

---

PureBasicIDE/Common.pb
PureBasicIDE/ProjectManagement.pb

If you trigger CloseProject(), for example by `Ctrl+Shift+W`, while a project is loading its sources, it crashes the IDE. This is easy to test with a large project that auto-opens many files.
This patch adds an `IsProjectBusy` flag to prevent the crash (and other odd project behaviors) by disallowing `CloseProject()` or `OpenProject()` while the current project is still busy loading (or closing) its files.

Prevent crash while loading a project

---

PureBasicIDE/Preferences.pb

When opening the Preferences window, and populating the ComboBox of default color schemes, this PR will automatically pre-select the user's current scheme (if it's one of those default schemes!).
This is more intuitive when opening the Color preferences, indicating what scheme is currently in use.

Show current scheme in ComboBox when opening Color Prefs

---

PureBasicIDE/ProjectManagement.pb

A minor text bug fix. To demonstrate:
1. Open the IDE
2. Open any PB Project and one or more files
3. **Drag the "Project" tab in the TabBar to any other position besides 0**
4. Open preferences
5. Change any preference (eg. toggle Splash Screen)
6. Hit OK or Apply preferences - **Whatever file tab is in the first position is renamed "> Project"** :warning: 
This happens because `UpdateProjectInfoPreferences()` assumes the "Project" tab is in position 0. It should locate it using `*ProjectInfo`.
Also, this PR removes the `> ` prefix, so it remains `Project` instead of suddenly changing to `> Project`. The prefix seems to be leftover from older versions, and it didn't get removed in this function.

Bug fix: Wrong tab can be labeled "Project"

---

PureBasicIDE/Common.pb
PureBasicIDE/Preferences.pb
PureBasicIDE/dialogs/Preferences.xml

A small feature I've wanted: Add PageUp / PageDown hotkeys to flip through the Preferences screens, regardless of where the focus is.
Only tested on Windows, but it's very basic and should work on others.
It edits `Preferences.xml` so a fresh `make` is required to regenerate `ide/Preferences.pb`!

Add PageUp/Dn shortcuts to step through Preferences screens

---

.gitignore
PureBasicIDE/PureBasicIDE.pbp

This patch leaves the "Default Target" as-is but adds **6 new project targets**, pre-defined for Windows/Linux/Mac at 32/64-bit.
The targets have correct Build dirs, executable extensions, icon formats, and compile constants. (Please verify!)
This makes it easier to get up-and-running with the repo, or avoid reconfiguring the targets whenever switching branches or updating. It also makes Build All work (though the other OSes will display as failures, unless you choose to disable those targets).
Other minor project improvements:
- add /NOEXT param when debugging the project, to avoid re-associating your PB file extensions
- remove "5.70" from the project name
- add *.patch and *.diff extensions to gitignore

Pre-define 6 cross-platform project targets

---

PureBasicIDE/SourceManagement.pb

Fix IDE Crash on MacOS with TouchBar.
Stackcorruption on RemoveSource.
Move FreeGadget to the end of Procedure.

Fix IDE Crash on MacOS with TouchBar

---

.gitignore
Documentation/HTML-BUILD.bat

In order to facilitate quick preview of PB Documentation while editing it, this commits adds the `Documentation\HTML-BUILD.bat` script, which takes parameters (de|en|fr|all) to build a specific locale or all of them at once.
The HTML files are built into the `HTML/` subfolder of each locale and the whole folder is deleted at each rebuild operation:
- `Documentation/English/HTML/`
- `Documentation/French/HTML/`
- `Documentation/German/HTML/`
The above HTML folders are excluded from the repository via newly added `.gitignore` rules.

PB Help Quick HTML Preview Build Script

---

.editorconfig
.gitattributes
AsciiDoc/DocMaker-Help.asciidoc
AsciiDoc/DocMaker-Tags.asciidoc
AsciiDoc/PB-Documentation-Guide.asciidoc
AsciiDoc/README.md
AsciiDoc/asciidoc2html.sh
AsciiDoc/inc_warn-editing.adoc
Documentation/DocMaker-Help.html
Documentation/DocMaker-Tags.html
Documentation/PB-Documentation-Guide.html

Move all the AsciiDoc source files, and their build script, to the newly added `/AsciiDoc/` (root) folder to prevent cluttering the repository with unnecessary sources.
The `AsciiDoc/` folder will allow to store documents images and other assets (e.g. for syntax highlighting PureBasic/SpiderBasic source code excerpts) separately from the output HTML docs (which are self-contained) without introducing extra files in the target folders of these documents.
- Create new `AsciiDoc/` folder and move therein all the `.asciidoc` sources and the converter script from `Documentation/`.
- Adapt the `asciidoc2html.sh` script to build the HTML docs in the `Documentation/` folder.
- Externalize the "DON'T EDIT THIS DOCUMENT!!!" HTML comments warning to `inc_warn-editing.adoc` and replace its occurrence …

Move AsciiDoc Sources to Dedicated Folder

---

Documentation/English/Reference/residents.txt

In PureBasic Help (English), `reference/prototypes`, add Prototypes to the list of allowed items in a resident file — (along with structures, interfaces, macros and constants. 
See #120 for more details.

PB Help EN » Residents: Add Prototypes

---

Documentation/French/Reference/general_rules.txt

At the beginning of the French PB documentation page _Règles de syntaxe générales_ there's an HTML table providing a sort of Table of Contents to the page topics. The last row of the table omitted a table cell  (which is empty), which caused the table borders to display oddly.
This commit adds the missing cell (`<td></td>`) to fix the problem an make all table borders look good.

PB Help FR: Fix Broken HTML Table in "Règles de syntaxe générales"

---

Documentation/English/Clipboard.txt
Documentation/English/File.txt
Documentation/English/FileSystem.txt
Documentation/English/Image.txt
Documentation/English/MainGuide/history.txt
Documentation/English/Reference/module.txt
Documentation/English/Reference/procedures.txt
Documentation/English/Sort.txt
Documentation/English/String.txt
Documentation/German/Reference/data.txt
Documentation/German/Toolbar.txt
Residents/Linux/gtk2/gtk/gtkaccellabel.pb
Residents/MacOS/Makefile

In many cases **separate** & **separately** were spelled incorrectly - fixed. Also fixed a few typos/grammar in the vicinity of the main fixes.

Fixed a number of typos (mostly misspelled 'separate/separately')

---

PureBasicIDE/PureBasicIDE.pbp

Change the "Executable format" for all 7 build targets from `console` to the default (GUI program).
When the format is default, and `cpu=0`, the IDE simply doesn't write the `<format>` XML node. That's why this PR is 7 line deletions.
Fixes issue #153

Change format for all build targets from 'console' to default

---

PureBasicIDE/FormDesigner/mainevents.pb
PureBasicIDE/PureBasic.pb

PR #131 (a bugfix for crash on MacOS Big Sur) introduced new bugs for me (on Windows). That's OK, it's why we have a `devel` branch :slightly_smiling_face: 
**Bug 1 (minor)** Since that PR, at IDE exit `FlushEvents()` is called *after closing all windows*. Since that procedure calls `WindowEvent()`, this causes 1–3 debugger errors, but they're not fatal.
**Bug 2 (major)** With the latest `devel` branch, run the IDE, open a Project, and *also* create a new Form. With both open, quit the IDE... I get an **Invalid Memory Access crash** on Windows. It is caused by the new `FlushEvents()` triggering a Form redraw on a gadget which no longer exists, and the `StartDrawing()` is not checked for success.
My patch for now is to safely check the `StartDrawing()` and also only call the extra …

Prevent debugger errors and IMA crash on quit

---

PureBasicIDE/SourceManagement.pb

**Existing behavior**: When closing a 'New' source, the Modified flag will prompt you to save changes, even if the source is totally empty. (For example, you test a couple lines of code, then delete them.) Prompting you to save an empty file seems unnecessary.
**New behavior**: If a modified source is 'New' *and also empty*, the prompt to save changes will be prevented. (In all other conditions, the behavior remains as-is.) Notepad++ and others do this.
Feature request on the forum: https://www.purebasic.fr/english/viewtopic.php?f=3&t=76834

Prevent the Save Changes prompt if a source is 'New' and also empty

---

AsciiDoc/PB-Library-SDK.asciidoc
PureBasicIDE/sdk/PB-Library-SDK.html

Fix a few typos in the "PureBasic Library SDK" document (see #139).

PB Library SDK Typos

---

AsciiDoc/DocMaker-Help.asciidoc
Documentation/DocMaker-Help.html

Fix Broken Links in DocMaker Help
In `DocMaker-Help.asciidoc`, update the download link for the "HTML Help Workshop" installer (fixes #149).
The "HTML Help Workshop" download page was removed from microsoft.com:
https://www.microsoft.com/en-us/download/details.aspx?id=21138
@Naheulf found that an archived copy of the installer can be downloaded via the Wayback Machine (Internet Archive); we now provide this link in the download instructions.
-------------------------------------------------------------------------------
For a live preview of the amended document:
- [`Documentation/DocMaker-Help.html`][DocMaker-Help.html]
[DocMaker-Help.html]: https://htmlpreview.github.io/?https://github.com/fantaisie-software/purebasic/blob/DocMaker-Help/Documentation/DocMaker-Help.html#_windows_chm_help …

Fix Broken Links in DocMaker Help

---

Documentation/French/Reference/residents.txt

In PureBasic Help (French), reference/prototypes, add Prototypes to the list of allowed items in a resident file — (along with structures, interfaces, macros and constants.
See #120 for more details.
Note: This is the French version of #121

PB Help FR » Residents: Add Prototypes

---

PureBasicIDE/AddTools.pb

The environment variable was updated only when the compiler compiled the
source code. Therefore, only the following tool trigger events resulted
in an update of the environment variable:
- `After Compile/Run`
- `After Create Executable`
PB_TOOL_Compiler update delayed
https://www.purebasic.fr/english/viewtopic.php?t=72110

Fix the updating of the `PB_TOOL_Compiler` environment variable

---

PureBasicIDE/AddTools.pb

The bug was introduced by the pull request "Fix the updating of the
`PB_TOOL_Compiler` environment variable (#191)".
PB6.0 GBeta 2 Crash on start
https://www.purebasic.fr/english/viewtopic.php?t=78496
v6 Beta 2 - Invalid memory access
https://www.purebasic.fr/english/viewtopic.php?t=78503

Fix crashing on IDE start/close, when a tool is set up to trigger in this case

---

validate.sh

Tweak the custom `validate.sh` script so the Travis CI build no longer
checks that PureBasic sources don't contain trailing spaces.
This check was performed via a custom Bash script, not via EClint,
so the `.editorconfig` settings were not affected by this commit.

Drop PB Trailing Spaces Validation

---

PureBasicIDE/ConstantsData.pbi
PureBasicIDE/MacExtensions.pb

Under macOS, the TabBarPanel no longer functions to switch between DarkMode and Aqua.
This is because the function 'GetTabBarGadgetItemColor' no longer returns the previously set color values (with alphachannel and signed).
The auto-completion for 'RemoveKeyboardShortcut' constants is not correct.

Small fix macOS darkmode and auto complete

---

PureBasicIDE/Macro.pb
PureBasicIDE/ProjectManagement.pb
PureBasicIDE/ScintillaHighlighting.pb
PureBasicIDE/SourceManagement.pb
PureBasicIDE/UserInterface.pb

Continuation of PR #167 to implement the functionality also for Linux. Thanks @kenmo-pb for the initial work.
I also added comments in an attempt to make it more clear where the enter key handling takes place on each OS.

Allow Enter key to open selected Project File in list (all platforms)

---

PureBasicIDE/SourceManagement.pb

* Clear old list of constants before reloading
* Properly reload (and cut) settings from temp files in case of `#SAVESETTINGS_DoNotSave`
See https://www.purebasic.fr/english/viewtopic.php?t=78735

Fixes for reloading of settings from temp files

---

PureBasicIDE/Declarations.pb
PureBasicIDE/StructureFunctions.pb

Bugfix for: https://www.purebasic.fr/english/viewtopic.php?t=61676
In addition to module prefixes, also improved handling of line continuations within a method prototype, e.g.:
```
Interface foo
bar(a, ; comment
b, ; comment
c) ; comment
EndInterface
```

Improve interface parser to deal with module prefixes and line continuations

---

PureBasicIDE/Common.pb
PureBasicIDE/ProjectManagement.pb

Project files keep their tab positions in the IDE.
Additionally I've added the project name to the Project tab (shown as: Project [Name], instead of just Project)
More or less that whole feature request from here:
https://www.purebasic.fr/english/viewtopic.php?t=66119

Keep order of project files

---

PureBasicIDE/EditHistory.pb

If the session history window was closed maximized then when restored the code view and tree view are not expanded to fill it.
https://www.purebasic.fr/english/viewtopic.php?t=76506

Fix the session history window resizing when restored maximized.  

---

Documentation/English/Array.txt
Documentation/German/Array.txt

- "In PureBasic" removed from the English and German versions because it was not worded that way in the French version either.
- English sentence corrected.
- English and German version better adapted to the French version.

Improve array overview note text

---

PureBasicIDE/ConstantsData.pbi
PureBasicIDE/ConstantsDataSpiderBasic.pbi

Fixes reported bug [no context-sensitive autocomplete for Base64Encoder and Base64EncoderBuffer flags] (https://www.purebasic.fr/english/viewtopic.php?t=82202)

Add missing autocomplete data for Base64Encoder and Base64EncoderBuffer.

---

PureBasicIDE/SourceManagement.pb

Removed a `FlushEvents()` call that messes up the file contents when switching tabs while loading many sources (for example on startup).
Note: The removed "fix" is very old and I cannot reproduce the behavior described in the old comments. So it probably does not apply anymore to the current version of Scintilla and other components. If the described behavior comes back we have to find a different solution for this.
See:
* https://www.purebasic.fr/english/viewtopic.php?t=76168
* https://www.purebasic.fr/english/viewtopic.php?f=18&t=71194
* https://www.purebasic.fr/english/viewtopic.php?f=23&t=69839

Remove an old Linux fix that causes problems when switching sources while loading a file

---

PureBasicIDE/ToolbarManagement.pb

See Topic: [Incomplete Preference Classic ToolBar](https://www.purebasic.fr/english/viewtopic.php?t=82483)
Since version 6.0, the Classic Toolbar in the preferences is incomplete, the theme icons are missing
And with the Default Toolbar there is an additional entry, Icon_24, Action_24 with indecipherable characters

Incomplete Preference Classic ToolBar

---

PureBasicIDE/ToolsPanel.pb

This PR resolves #252, ensuring DPI scaling is accounted for when hit-testing against the ToolsPanel in auto-hide mode.

fix(ToolsPanel): respect DPI scaling for panel hit-test region

---

PureBasicIDE/ToolsPanel.pb

This PR resolves a flickering issue mentioned in the conversation at https://github.com/fantaisie-software/purebasic/issues/252#issuecomment-1751737019, where the editing area and toolbar tends to flicker when hiding the ToolsPanel.
I tried a few approaches to avoid the flickering here, but temporarily pausing main-window painting with WM_SETREDRAW seemed to be the solution with least flickering. (Pausing just the editor area works, but then the toolbar flickers, so would have to be separately paused as well)
I have to admit I'm unfamiliar with the `SplitterGadget`, so there might be a better way to deal with the reparenting here without relying on WM_SETREDRAW.

fix(ToolsPanel): avoid flicker when hiding panel

---

Documentation/English/Thread.txt
Documentation/German/Thread.txt

`@NoParameters` was written as `@NoParameter` in the English and German docs for CreateMutex(). French was uneffected.

Fixed a typo in the English and German docs causing CreateMutex() to not show a parameter list.

---

PureBasicIDE/LinuxHelp.pb

PB-Help crashed on Ubuntu 24.04
Move update help contents to main event loop.

Linux Help Window Fix
