fantaisie-software/purebasic

PureBasicIDE/data/SilkTheme/README.md
In `PureBasicIDE/data/SilkTheme/`, create a markdown version of the `Readme.txt` file containing previews of all the icons.
Original `Readme.txt` file preserved.
=> Silk Icons Preview

PureBasicIDE/FormDesigner/img/README.md, PureBasicIDE/data/DefaultTheme/README.md, PureBasicIDE/data/SilkTheme/README.md
Add `README.md` files with previews of image contents to the following folders:
PureBasicIDE/FormDesigner/img/
PureBasicIDE/data/DefaultTheme/
Tweak existing `README.md` to make it consistent with the other images previews:
PureBasicIDE/data/SilkTheme/
Wherever possible, credit image authors and provide back-links.
=> Icons & Images Previews

PureBasicIDE/UpdateCheck.pb
Forum thread: [PB-IDE: No automatic update notification](https://www.purebasic.fr/english/viewtopic.php?f=23&t=73609)
Please note that the fix was not tested.
=> Fix the weekly update check

PureBasicIDE/libmba/README.md, README.md
In `PureBasicIDE/libmba/` add README file with information about the library, its author and license, and how its used in the project.
In main `README.md` add libmba to the "Credits" section. (See #21)
=> Libmba Info and Credits

PureBasicIDE/EditHistory.pb
Purge sessions from the Session History list if they don't have any contents.
These "empty" sessions just clutter up the list. Currently you need an IDE tool to remove them.
https://www.purebasic.fr/english/viewtopic.php?f=3&t=65019
https://www.purebasic.fr/english/viewtopic.php?f=3&t=73336
In this pull request, this is enabled or disabled at compile-time by a new constant.
If there is really some value in showing "empty" sessions, then I can extend this feature to be a user-toggled setting. Thoughts?
=> Purge empty sessions from Session History list

PureBasicIDE/PureBasic IDE.pbp
Three files were recently renamed (PR #56).
This new PR updates the references in the PBP project file to the new names.
=> Update project PBP file to use renamed files

PureBasicIDE/FormDesigner/imageslistwindow.pb, PureBasicIDE/FormDesigner/mainevents.pb, PureBasicIDE/Language.pb
1. The file picker has now the correct pattern.
2. The Image Manager has now a title. Needs to be added in the language catalogs, i guess?
3. The size of the window is now bigger.
4. Window can be maximized.
5. The 1. column is wider so you can read more of the imagepath.
6. The last two columns are wider so the text of the buttons fit in all languages.
After:
Before:
=> Image Manager - small bug fix and gui improvement

CONTRIBUTING.md, README.md
The goal of this PR is to update all the documentation in the repository regarding contributing to the project, in view of the `devel` branch approach proposed in #84.
- [`CONTRIBUTING.md`][CONTRIBUTING] document (link points to edited section)
It's currently still a draft and needs further discussing (e.g. we could mention that long-term experimental features might use a different branch as baseline, etc.).
Possibly, the main README document might also need to be edited in view of the new workflow (haven't checked it yet).
[CONTRIBUTING]: https://github.com/fantaisie-software/purebasic/blob/devel-instructions/CONTRIBUTING.md#contributing-to-the-repository "View the CONTRIBUTING document from the PR branch"
=> Update CONTRIBUTING Doc

PureBasicIDE/SourceManagement.pb
Old (own) request finally fullfilled:
https://www.purebasic.fr/english/viewtopic.php?f=18&t=70641
=> Check for external tools, when opening files

CollectLanguage/CollectLanguage.pb
Cleanup `CollectLanguage/CollectLanguage.pb` so that it passes Travis CI code styles validation.
=> Code Styles Clean Up

Documentation/DocMaker-Help.asciidoc, Documentation/DocMaker-Help.html, Documentation/DocMaker-Tags.asciidoc, Documentation/DocMaker-Tags.html, Documentation/PB-Documentation-Guide.asciidoc, Documentation/PB-Documentation-Guide.html
I've now also converted the DocMaker Help, taken from the `SDK\DocMaker\Readme.txt` document, and renamed it as `DocMaker-Help.asciidoc`.
An HTML converted version of the document was also added, for the benefit end users:
- [`DocMaker-Help.html`](http://htmlpreview.github.io/?https://github.com/fantaisie-software/purebasic/blob/pb-docs/Documentation/DocMaker-Help.html)
I've taken the liberty to polish and improve the original document contents in various ways, to better fit the new format and because I needed to update the obsolete link to the SVN repository.
Even though that part of the SDK is not part of this repo, I thought it would be good to have an updated version of this document inside the `Documentation/` folder, since end users might need it for contributing to the project.
If …
=> DocMaker Help in AsciiDoc

Documentation/English/Reference/general_rules.txt
Polish the English text of the "General Syntax Rules" section.
=> PB Help EN: General Syntax Rules

AsciiDoc/CompilerInterface.asciidoc, AsciiDoc/DocMaker-Help.asciidoc, AsciiDoc/DocMaker-Tags.asciidoc, AsciiDoc/PB-DLL-Importer.asciidoc, AsciiDoc/PB-Documentation-Guide.asciidoc, AsciiDoc/PB-Library-SDK.asciidoc, AsciiDoc/PureUnit-Help.asciidoc, AsciiDoc/README.md, AsciiDoc/asciidoc2html.sh, AsciiDoc/inc_contributing.adoc, Documentation/DocMaker-Help.html, Documentation/DocMaker-Tags.html, Documentation/PB-Documentation-Guide.html, PureBasicIDE/sdk/CompilerInterface.html, PureBasicIDE/sdk/PB-DLL-Importer.html, PureBasicIDE/sdk/PB-Library-SDK.html, PureBasicIDE/sdk/PureUnit-Help.html
New SDK Docs Ported to AsciiDoc
The following documents from the PureBasic 5.73 SDK (Windows) were ported from plain-text to AsciiDoc and added to the project (click on titles for Live Previews):
|         doc title         |       original SDK file       |
|---------------------------|-------------------------------|
| _[PureUnit Help]_         | `SDK\PureUnit\Readme.txt`     |
| _[PB Compiler Interface]_ | `SDK\CompilerInterface.txt`   |
| _[PB Library SDK]_        | `SDK\Readme.txt`              |
| _[PB DLL Importer]_       | `SDK\DLL Importer\Readme.txt` |
The original English text has been polished and adapted to the AsciiDoc formatting standards; but beside these aesthetic tweaks, the original text wasn't altered in any meaningful way.
Some of these documents are quite outdated — …
=> New SDK Docs Ported to AsciiDoc

Documentation/French/Process.txt
=> Fix ReadProgramString() and few typos in fr doc

PureBasicIDE/SourceParser.pb
Fix for https://www.purebasic.fr/english/viewtopic.php?t=78576
=> Exclude enumeration names from variable parsing

PureBasicIDE/Common.pb, PureBasicIDE/Declarations.pb, PureBasicIDE/LinuxExtensions.pb, PureBasicIDE/MacExtensions.pb, PureBasicIDE/ProcedureBrowser.pb, PureBasicIDE/SourceManagement.pb, PureBasicIDE/WindowsExtensions.pb
See https://www.purebasic.fr/english/viewtopic.php?p=564227#p564227
=> Remember ProcedureBrowser scroll position

PureBasicIDE/AutoComplete.pb
Allow non-PB constants in context-sensitive AutoComplete mode if the typed word does not start with `#PB` (for WinAPI constants etc.)
See here https://www.purebasic.fr/english/viewtopic.php?p=588539#p588539
Implementation is a little bit different to allow for `#True` and `#False` in context sensitive mode and allow the prefix word to be only `#P`.
=> Disable context-sensitive AutoComplete for non-PB constants

PureBasicIDE/SourceManagement.pb
Bugfix for https://www.purebasic.fr/english/viewtopic.php?t=78958
=> Fix file monitor in case multiple files change at once

PureBasicIDE/SourceParser.pb
Bugfix for https://www.purebasic.fr/english/viewtopic.php?t=60691
=> Ignore start constant when parsing enumerations

PureBasicIDE/FindWindow.pb
Undo/Redo done in one Go, after a "Replace All". 
See: https://www.purebasic.fr/english/viewtopic.php?p=592319#p592319
=> Replace All Undo/Redo

PureBasicIDE/AutoComplete.pb, PureBasicIDE/SourceParser.pb
Two fixes (I hope) for autocomplete.
More info 
https://www.purebasic.fr/english/viewtopic.php?t=80617
https://www.purebasic.fr/english/viewtopic.php?t=59911
=> Autocomplete fixes

PureBasicIDE/ConstantsData.pbi
ConstantsData:
- Added missing constants for Pitch and Yaw
- Added missing constants for Roll
=> Some fixed for v6.02 Beta 3

PureBasicIDE/ScintillaHighlighting.pb
See https://www.purebasic.fr/english/viewtopic.php?t=81602
=> - Fix indentation of line continuations after 'ProcedureReturn'

PureBasicIDE/SourceParser.pb
See https://www.purebasic.fr/english/viewtopic.php?t=81506
=> Fix source parser for module prefix in 'Define' or similar keywords

PureBasicIDE/HighlightingEngine.pb
See https://www.purebasic.fr/english/viewtopic.php?t=81781
=> Remove highlighting of inline ASM/C comments due to ambiguity with inline C

PureBasicIDE/HighlightingEngine.pb
See https://www.purebasic.fr/english/viewtopic.php?t=80281
=> Fix highlighting for TODO comments with multibyte utf8 characters

PureBasicIDE/FileSystem.pb
See https://www.purebasic.fr/english/viewtopic.php?t=77907
=> Remove redundant separators from paths when comparing for equality

PureBasicIDE/FormDesigner/FormManagement.pb, PureBasicIDE/FormDesigner/codeviewer.pb, PureBasicIDE/FormDesigner/declare.pb, PureBasicIDE/FormDesigner/mainevents.pb, PureBasicIDE/FormDesigner/opensave.pb
Added WebViewGadget to FormDesigner
- Common variable / constant name and counter for WebGadget and WebViewGadget. So compatible for old form files.
- Change control name WebView to Web for WebGadget
- Added control name WebView for WebViewGadget
- Added Flags for WebGadget
- Added Flags for WebViewGadget
- Added EventType for ListIconGadget and ExplorerListGadget
=> FormDesigner Added WebViewGadget
